language: ruby
rvm:
  - 2.1.5
cache: bundler
before_script:
  - bundle exec thor setup:dev_env
  - bundle exec rake db:create db:migrate
branches:
  only:
    - master
    - develop
notifications:
  webhooks: https://hooks.slack.com/services/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
