development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || '779a989560545187f66c9783dd837e4b9b7aa7051d3e6b34f35d3af313a129ab9fc33102c86f60771237fefc85b686d31c878e0b853d23f45e091b2528fb41bf' %>
  devise: <%= ENV["DEVISE_SECRET"] || '779a989560545187f66c9783dd837e4b9b7aa7051d3e6b34f35d3af313a129ab9fc33102c86f60771237fefc85b686d31c878e0b853d23f45e091b2528fb41bf' %>
  devise_otp: <%= ENV["DEVISE_OTP_SECRET"] || '779a989560545187f66c9783dd837e4b9b7aa7051d3e6b34f35d3af313a129ab9fc33102c86f60771237fefc85b686d31c878e0b853d23f45e091b2528fb41bf' %>
  devise_otp_issuer: Reckoning.io
  ga: <%= ENV["GOOGLE_ANALYTICS"] %>
  base:
    registration: <%= ENV["SETTING_REGISTRATION"] %>
    demo: <%= ENV["SETTING_DEMO"] %>
  mailer:
    default_from: noreply@reckoning.io
    host: <%= ENV["SMTP_HOST"] %>
    port: <%= ENV["SMTP_PORT"] %>
    user: <%= ENV["SMTP_USER"] %>
    password: <%= ENV["SMTP_PASSWORD"] %>
  url: http://reckoning.dev
  domain: reckoning.dev
  dropbox_key: <%= ENV["DROPBOX_KEY"] %>
  dropbox_secret: <%= ENV["DROPBOX_SECRET"] %>
  intercom: <%= ENV["INTERCOM"] %>
  sentry_js: <%= ENV["SENTRY_JS"] %>
  aws_s3:
    key_id: <%= ENV["AWS_S3_KEY_ID"] %>
    access_key: <%= ENV["AWS_S3_ACCESS_KEY"] %>
    bucket: reckoningdev
  stripe:
    secret_key: <%= ENV["STRIPE_SECRET"] %>
    public_key: <%= ENV["STRIPE_PUBLIC"] %>
test:
  secret_key_base: secret
  devise: devise
  devise_otp: devise_otp
  devise_otp_issuer: Reckoning.io
  ga:
  base:
    registration: true
    demo: false
  mailer:
    default_from: noreply@reckoning.io
    host:
    port:
    user:
    password:
  url: http://reckoning.dev
  domain: reckoning.dev
  dropbox_key:
  dropbox_secret:
  intercom:
  sentry_js:
  stripe:
    secret_key:
    public_key:
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  devise: <%= ENV["DEVISE_SECRET"] %>
  devise_otp: <%= ENV["DEVISE_OTP_SECRET"] %>
  devise_otp_issuer: Reckoning.io
  ga: <%= ENV["GOOGLE_ANALYTICS"] %>
  base:
    registration: <%= ENV["SETTING_REGISTRATION"] %>
    demo: <%= ENV["SETTING_DEMO"] %>
  mailer:
    default_from: noreply@reckoning.io
    host: <%= ENV["SMTP_HOST"] %>
    port: <%= ENV["SMTP_PORT"] %>
    user: <%= ENV["SMTP_USER"] %>
    password: <%= ENV["SMTP_PASSWORD"] %>
  url: <%= ENV["APP_URL"] %>
  domain: <%= ENV["DOMAIN"] %>
  dropbox_key: <%= ENV["DROPBOX_KEY"] %>
  dropbox_secret: <%= ENV["DROPBOX_SECRET"] %>
  intercom: <%= ENV["INTERCOM"] %>
  sentry_js: <%= ENV["SENTRY_JS"] %>
  aws_s3:
    key_id: <%= ENV["AWS_S3_KEY_ID"] %>
    access_key: <%= ENV["AWS_S3_ACCESS_KEY"] %>
    bucket: reckoning
  stripe:
    secret_key: <%= ENV["STRIPE_SECRET"] %>
    public_key: <%= ENV["STRIPE_PUBLIC"] %>
