production:
  secret_key_base: rails_secret_base
  devise: devise_secret
  sentry: sentry
  ga:
  base:
    registration: true
    demo: true
  mailer:
    default_from: reckoning@example.com
    host:
    port:
    user:
    password:
  url: "http://reckoning.dev"
  domain: "reckoning.dev"
  dropbox_key:
  dropbox_secret:
development:
  secret_key_base: rails_secret_base
  devise: devise_secret
  sentry: sentry
  ga:
  base:
    registration: true
    demo: true
  mailer:
    default_from: reckoning@example.com
    host:
    port:
    user:
    password:
  url: "http://reckoning.dev"
  domain: "reckoning.dev"
  dropbox_key:
  dropbox_secret:
test:
  secret_key_base: rails_secret_base
  devise: devise_secret
  sentry: sentry
  ga:
  base:
    registration: true
    demo: true
  mailer:
    default_from: reckoning@example.com
    host:
    port:
    user:
    password:
  url: "http://reckoning.dev"
  domain: "reckoning.dev"
  dropbox_key:
  dropbox_secret:
